### ISSUE TITLE
ACCOUNT NOTIFICATIONS not saved on profile

### ISSUE THREAD

**Issue by dvoet** [DataBiosphere/terra-ui#1381] opened 2019-04-03 02:20 UTC
on the user profile page, when I change notification options at the bottom and click save, they are not saved.

**Comment by katevoss** [comment] 2019-04-03 13:34
I believe this is a dupe of #1237

**Comment by katevoss** [comment] 2019-04-04 15:03
@dvoet a fix for #1237 was just released, are you able to reproduce this issue?

**Closed** 2019-04-22 17:06 UTC
