### ISSUE TITLE
Track "Opted-Out" Users

### ISSUE THREAD

**Issue by kleighwe** [DataBiosphere/terra-ui#1424] opened 2019-04-11 18:18 UTC
We must collect the emails of users who choose to opt-out. These should be easy to aggregate and deliver to customer success for followup.

Dependent on answer to "Opt out" question (#1422)

**Comment by bradtaylor** [comment] 2019-04-12 16:31
@davidangb If we are storing the opt-out decision in thurloue per #1422, and Thurloe values are in BigQuery, is there anything to actually do here?

**Comment by bradtaylor** [comment] 2019-04-12 18:43
Brad will confirm with Alex that this is a no-op from the Terra perspective

**Comment by bradtaylor** [comment] 2019-04-22 17:26
Confirmed it as a no-op. Closing this story as "invalid" because there turns out to be nothing to do

**Closed by bradtaylor** 2019-04-22 17:26 UTC
Labels: 2019-April, invalid
