### ISSUE TITLE
Add search functionality to the Job History page

### ISSUE THREAD

**Issue by ruchim** [DataBiosphere/terra-ui#1324] opened 2019-03-22 14:31 UTC
In FireCloud today, I rely on the search bar on the Monitor tab to filter down results. 

For example, I was looking for an old job using cell-ranger in the past, and I was able to find the exact job quickly in FireCloud:
<img width="1326" alt="Screen Shot 2019-03-22 at 10 27 59 AM" src="https://user-images.githubusercontent.com/14941133/54829722-6596eb80-4c8d-11e9-8ec1-fdef22c7fd8e.png">

Trying to find the same job in the same workspace in Terra, I tried using the ctrl+f functionality to search for the same keyword, which didn't work:
<img width="1378" alt="Screen Shot 2019-03-22 at 10 28 45 AM" src="https://user-images.githubusercontent.com/14941133/54829704-5dd74700-4c8d-11e9-893c-bb7b7779a531.png">

I eventually find my job after lots of scrolling, but that was quite tedious because in this case its a fairly old job. 

AC: It would be great to have a search bar or a filter bar or someway to easily to search for old jobs.

**Comment by bradtaylor** [comment] 2019-03-22 21:24
FireCloud tables had a filter bar that applied to any column, as @ruchim notes. Other users have asked for this on our data tables.
I think we need at least this single-searchbar functionality on all tables.

**Comment by zarsky-broad** [comment] 2019-04-18 16:01
Closing as duplicate of #1443

**Closed by zarsky-broad** 2019-04-18 16:01 UTC
Labels: 2019-Q2, Beta-response, duplicate
