### ISSUE TITLE
Hitting the pause button on compute runtime UI boots me to workspace

### ISSUE THREAD

**Issue by sharmatime** [DataBiosphere/terra-ui#1384] opened 2019-04-03 18:29 UTC
When I'm in a notebook with an active running cluster, and hit the pause button, the UI sends me back out to the workspace, but doesn't pause my cluster. Not sure about the intended behavior - is it meant to stop the cluster and boot me back to the notebook tab on the workspace?

**Comment by breilly2** [comment] 2019-04-03 18:33
Are you sure it doesn't pause the cluster? We are aware of the fact that changes in status are not immediately reflected in Terra UI (because Leo is sometimes delayed giving us the updated status when it changes).

**Comment by katevoss** [comment] 2019-04-18 19:08
I think I know what's going on! When a user clicks "Pause" or "Delete" while they are on the cluster, they are sent to the list of Notebooks, as designed. However I think this is canceling the Leo call because they left the page, so it is not actually pausing or deleting their cluster.

**Comment by zarsky-broad** [comment] 2019-04-18 20:08
Yup. We had a PR somewhere that fixed this, it might be my one that's on hold right now?

**Comment by sharmatime** [comment] 2019-05-03 21:57
I've also found this is true when you're on the terminal UI in Terra. If you hit the pause button from the terminal page it boots me back to the workspace but doesn't pause my cluster.

**Comment by katevoss** [comment] 2019-05-14 14:12
This is now fixed, if you're still having this issue let us know!

**Closed by katevoss** 2019-05-14 14:12 UTC

**Comment by mbookman** [comment] 2019-05-17 21:08
Tested this and the behavior is great. Thanks!
