### ISSUE TITLE
Provide email alternative in event of contact-us error

### ISSUE THREAD

**Issue by bradtaylor** [DataBiosphere/terra-ui#977] opened 2018-12-10 19:26 UTC
if the contact us widget generates any error, we provide a mailto link pre-populated with the error they entered, that they can click on in order to contact us at our support email

**Comment by katevoss** [comment] 2019-05-14 15:50
I'm not able to reproduce this, and I checked with Sushma and she hasn't gotten reports of issues using the widget from users. Should I close this and we'll reopen if users report this being an issue?

**Comment by breilly2** [comment] 2019-05-14 16:09
How would we know that users didn't see errors with this if we haven't been giving them an alternate means of contacting us? This wasn't ever something that we were able to reproduce. It was accounting for potential problems and making sure we were taking every effort we could to let users contact us when their attitude toward the platform may already be somewhat fragile.

**Comment by katevoss** [comment] 2019-05-14 18:04
That's a good point and considering that if this is a problem, it would be a silent failure.

**Closed** 2019-05-15 20:02 UTC
